import type { Category, Professional } from "@/types/marketplace";

export const categories: Category[] = [
  { slug: "legal", label: "Legal", description: "Abogados corporativos y litigio", color: "bg-emerald-700" },
  { slug: "contabilidad", label: "Contabilidad", description: "Fiscal, auditoría y nóminas", color: "bg-slate-700" },
  { slug: "ingenieria", label: "Ingeniería", description: "Civil, industrial y proyectos", color: "bg-teal-700" },
  { slug: "arquitectura", label: "Arquitectura", description: "Diseño y dirección de obra", color: "bg-emerald-800" },
  { slug: "consultoria", label: "Consultoría", description: "Estrategia y operaciones", color: "bg-slate-600" },
  { slug: "recursos-humanos", label: "RR. HH.", description: "Selección y compliance laboral", color: "bg-teal-800" },
];

const img = (id: string, w = 400, h = 400) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&h=${h}&fit=crop&crop=faces`;

export const professionals: Professional[] = [
  {
    id: "1",
    name: "Dra. Elena Vázquez",
    title: "Abogada mercantil · M&A",
    category: "Legal",
    categorySlug: "legal",
    bio: "Más de 12 años asesorando pymes y fondos en operaciones societarias, due diligence y contratos comerciales internacionales.",
    bioShort: "M&A, contratos y compliance societario para empresas en crecimiento.",
    rating: 4.9,
    reviewCount: 186,
    priceChat: 4.5,
    priceVoice: 6.2,
    priceVideo: 8.5,
    image: img("1573496359142-b8d87734a5a2"),
    status: "online",
    videoAvailable: true,
    servicesCount: 842,
    likes: 3120,
    repeatClients: 64,
    queueCount: 3,
    tagline: "Claridad legal para decisiones de negocio.",
    aboutServices:
      "Sesiones de consulta express por chat, llamada o videollamada. Revisión de borradores, estrategia en negociaciones y acompañamiento puntual en cierres.",
    aboutMe:
      "Licenciada por la UNAM, LL.M. en Londres. He liderado el área legal de dos scale-ups y actualmente combino despacho boutique con mentoría a founders. Me enfoco en que entiendas el riesgo real, no el teórico.\n\nPublico una newsletter quincenal sobre gobierno corporativo y participo como speaker en foros de venture capital.",
    specialties: [
      { label: "Contratos", icon: "doc" },
      { label: "M&A", icon: "merge" },
      { label: "Startup", icon: "rocket" },
      { label: "IP", icon: "shield" },
    ],
    featuredReview:
      "Resolvió nuestra ronda Serie A en tiempo récord; explicaciones claras y sin jerga innecesaria.",
    reviews: [
      { id: "r1", author: "Carlos M.", date: "2026-03-02", text: "Excelente criterio en la due diligence. Muy recomendable.", rating: 5 },
      { id: "r2", author: "Inversiones Norte", date: "2026-02-18", text: "Profesional, puntual y accesible por videollamada.", rating: 5 },
      { id: "r3", author: "Laura P.", date: "2026-01-10", text: "Nos ayudó a reestructurar acuerdos con proveedores clave.", rating: 5 },
    ],
  },
  {
    id: "2",
    name: "Lic. Miguel Herrera",
    title: "Contador público · Fiscal",
    category: "Contabilidad",
    categorySlug: "contabilidad",
    bio: "Especialista en optimización fiscal legal para empresas de servicios y comercio electrónico.",
    bioShort: "Declaraciones, planeación fiscal y auditorías internas.",
    rating: 4.8,
    reviewCount: 124,
    priceChat: 3.2,
    priceVoice: 4.8,
    priceVideo: 6.0,
    image: img("1560250097-0b93528c311a"),
    status: "busy",
    videoAvailable: true,
    servicesCount: 620,
    likes: 1890,
    repeatClients: 58,
    queueCount: 5,
    tagline: "Números ordenados, decisiones más simples.",
    aboutServices:
      "Diagnóstico fiscal express, revisión de CFDI, proyecciones trimestrales y acompañamiento ante requerimientos del SAT (simulado en demo).",
    aboutMe:
      "CPC con maestría en finanzas. Trabajé ocho años en Big Four y ahora asesoro a empresas medianas en transformación digital contable.",
    specialties: [
      { label: "SAT", icon: "calc" },
      { label: "NIF", icon: "book" },
      { label: "Nóminas", icon: "users" },
    ],
    featuredReview: "Pasamos de caos a un calendario fiscal claro en tres sesiones.",
    reviews: [
      { id: "r1", author: "PMI Labs", date: "2026-03-01", text: "Muy didáctico y paciente con el equipo no financiero.", rating: 5 },
    ],
  },
  {
    id: "3",
    name: "Ing. Sofía Ramírez",
    title: "Ingeniera estructural",
    category: "Ingeniería",
    categorySlug: "ingenieria",
    bio: "Cálculo y revisión de estructuras para obra civil e industrial; normativas locales e internacionales.",
    bioShort: "Memorias de cálculo, refuerzos y visitas de obra virtual.",
    rating: 5.0,
    reviewCount: 98,
    priceChat: 5.0,
    priceVoice: 7.5,
    priceVideo: 9.0,
    image: img("1580489944761-15a19d654956"),
    status: "online",
    videoAvailable: true,
    servicesCount: 410,
    likes: 1420,
    repeatClients: 42,
    queueCount: 2,
    tagline: "Seguridad estructural con visión práctica.",
    aboutServices:
      "Revisión de planos, propuestas de refuerzo, coordinación con arquitectos y due diligence técnica pre-compra.",
    aboutMe:
      "Doctora en ingeniería, certificaciones en sismorresistencia. Colaboro con estudios de arquitectura en CDMX y Monterrey.",
    specialties: [
      { label: "Cálculo", icon: "grid" },
      { label: "Obra", icon: "building" },
      { label: "Normas", icon: "check" },
    ],
    featuredReview: "Detectó un detalle crítico antes de licitar; nos ahorró semanas.",
    reviews: [{ id: "r1", author: "Arq. Vega", date: "2026-02-20", text: "Imprescindible para proyectos medianos.", rating: 5 }],
  },
  {
    id: "4",
    name: "Arq. Daniel Ortega",
    title: "Arquitecto · Dirección de obra",
    category: "Arquitectura",
    categorySlug: "arquitectura",
    bio: "Residencial y corporativo; supervisión digital de avance y control de calidad en sitio.",
    bioShort: "Concepto, licencias y supervisión remota de obra.",
    rating: 4.7,
    reviewCount: 76,
    priceChat: 4.0,
    priceVoice: 5.5,
    priceVideo: 7.0,
    image: img("1472094153961-00e8a3b76b1a"),
    status: "offline",
    videoAvailable: false,
    servicesCount: 290,
    likes: 980,
    repeatClients: 31,
    queueCount: 0,
    tagline: "Obra alineada al diseño y al presupuesto.",
    aboutServices:
      "Briefing inicial, revisión de anteproyecto, visitas programadas por videollamada y bitácora de avances.",
    aboutMe:
      "Socio en estudio boutique; enfoque en eficiencia energética y materiales locales.",
    specialties: [
      { label: "Licencias", icon: "doc" },
      { label: "Obra", icon: "building" },
      { label: "Sostenible", icon: "leaf" },
    ],
    featuredReview: "Comunicación clara con el contratista; menos fricciones en obra.",
    reviews: [],
  },
  {
    id: "5",
    name: "MBA Ana Gómez",
    title: "Consultora estrategia & ops",
    category: "Consultoría",
    categorySlug: "consultoria",
    bio: "Rediseño de procesos, OKRs y tableros ejecutivos para equipos de 20–200 personas.",
    bioShort: "Diagnóstico operativo y planes de 90 días.",
    rating: 4.9,
    reviewCount: 201,
    priceChat: 5.5,
    priceVoice: 8.0,
    priceVideo: 10.0,
    image: img("1594744803329-e58b31de8bf5"),
    status: "online",
    videoAvailable: true,
    servicesCount: 512,
    likes: 2670,
    repeatClients: 55,
    queueCount: 4,
    tagline: "Operaciones que escalan sin perder control.",
    aboutServices:
      "Workshops remotos, diseño de KPIs, acompañamiento a PMO y sesiones de troubleshooting con liderazgo.",
    aboutMe:
      "Ex-directora de operaciones en retail y SaaS B2B; certificada en lean six sigma.",
    specialties: [
      { label: "OKR", icon: "target" },
      { label: "Procesos", icon: "flow" },
      { label: "PMO", icon: "kanban" },
    ],
    featuredReview: "En seis semanas bajamos lead time de soporte un 28%.",
    reviews: [
      { id: "r1", author: "TechFlow", date: "2026-03-05", text: "Datos accionables desde la primera sesión.", rating: 5 },
    ],
  },
  {
    id: "6",
    name: "Lic. Patricia Ruiz",
    title: "RR. HH. · Compliance laboral",
    category: "RR. HH.",
    categorySlug: "recursos-humanos",
    bio: "Contratos, políticas internas, investigaciones laborales y cultura organizacional.",
    bioShort: "Nómina estratégica y prevención de riesgos laborales.",
    rating: 4.8,
    reviewCount: 89,
    priceChat: 3.8,
    priceVoice: 5.2,
    priceVideo: 6.5,
    image: img("1551836022-d5d88e9218df"),
    status: "online",
    videoAvailable: true,
    servicesCount: 355,
    likes: 1100,
    repeatClients: 48,
    queueCount: 1,
    tagline: "Equipos alineados y normativa al día.",
    aboutServices:
      "Revisiones de contrato, manuales, protocolos de home office y simulacros de entrevistas ejecutivas.",
    aboutMe:
      "Maestría en derecho laboral; experiencia in-house en manufactura y servicios financieros.",
    specialties: [
      { label: "Contratos", icon: "doc" },
      { label: "Cultura", icon: "users" },
      { label: "Compliance", icon: "shield" },
    ],
    featuredReview: "Implementamos políticas híbridas sin fricción legal.",
    reviews: [],
  },
  {
    id: "7",
    name: "Dr. Javier Núñez",
    title: "Abogado litigio civil",
    category: "Legal",
    categorySlug: "legal",
    bio: "Estrategia procesal, medios alternos y negociación en conflictos comerciales de alto valor.",
    bioShort: "Litigio y arbitraje con enfoque en resultados.",
    rating: 4.6,
    reviewCount: 54,
    priceChat: 6.0,
    priceVoice: 9.0,
    priceVideo: 11.0,
    image: img("1519085360751-af0119f7cbe7"),
    status: "busy",
    videoAvailable: true,
    servicesCount: 180,
    likes: 720,
    repeatClients: 22,
    queueCount: 6,
    tagline: "Defensa técnica y comunicación clara al cliente.",
    aboutServices:
      "Análisis de viabilidad, preparación de demandas y defensas, y acompañamiento en audiencias (referencia simulada).",
    aboutMe:
      "Socio en bufete regional; docente en posgrado de derecho procesal.",
    specialties: [
      { label: "Litigio", icon: "hammer" },
      { label: "Arbitraje", icon: "scale" },
    ],
    featuredReview: "Realista sobre probabilidades; evitó un juicio largo innecesario.",
    reviews: [],
  },
  {
    id: "8",
    name: "Ing. Roberto Silva",
    title: "Ingeniero industrial · Supply",
    category: "Ingeniería",
    categorySlug: "ingenieria",
    bio: "Optimización de cadena de suministro, layout de planta y costos logísticos.",
    bioShort: "Diagnóstico de planta y simulación de escenarios.",
    rating: 4.9,
    reviewCount: 67,
    priceChat: 4.2,
    priceVoice: 6.0,
    priceVideo: 7.5,
    image: img("1507003211169-0a1dd7228f2d"),
    status: "online",
    videoAvailable: false,
    servicesCount: 240,
    likes: 890,
    repeatClients: 36,
    queueCount: 2,
    tagline: "Menos inventario, misma cobertura de servicio.",
    aboutServices:
      "Mapas de flujo, análisis ABC, propuestas de layout y tableros de abasto.",
    aboutMe:
      "IE graduate; consultor independiente para retail y alimentos.",
    specialties: [
      { label: "Supply", icon: "truck" },
      { label: "Layout", icon: "grid" },
    ],
    featuredReview: "Identificó cuellos de botella en una sola visita virtual.",
    reviews: [],
  },
];

export function getProfessionalById(id: string): Professional | undefined {
  return professionals.find((p) => p.id === id);
}

export const adminProviders = [
  { id: "p1", name: "Carlos López", email: "carlos@mail.com", category: "Legal", status: "pending" as const, docs: 3 },
  { id: "p2", name: "María Soto", email: "maria@mail.com", category: "Contabilidad", status: "approved" as const, docs: 5 },
  { id: "p3", name: "Luis Paredes", email: "luis@mail.com", category: "Ingeniería", status: "pending" as const, docs: 2 },
];

export const adminClients = [
  { id: "c1", name: "Empresa Alfa", email: "contacto@alfa.com", active: true },
  { id: "c2", name: "Beta Startups", email: "hola@beta.io", active: true },
  { id: "c3", name: "Gamma SA", email: "ops@gamma.mx", active: false },
];
